2022-04-04 10:54:46,798 INFO    MainThread:14853 [wandb_setup.py:_flush():75] Loading settings from /share/etud/e2008984/.config/wandb/settings
2022-04-04 10:54:46,798 INFO    MainThread:14853 [wandb_setup.py:_flush():75] Loading settings from /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/settings
2022-04-04 10:54:46,798 INFO    MainThread:14853 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-04 10:54:46,798 INFO    MainThread:14853 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-04 10:54:46,798 INFO    MainThread:14853 [wandb_init.py:_log_setup():405] Logging user logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220404_105446-3pzfqp1j/logs/debug.log
2022-04-04 10:54:46,799 INFO    MainThread:14853 [wandb_init.py:_log_setup():406] Logging internal logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220404_105446-3pzfqp1j/logs/debug-internal.log
2022-04-04 10:54:46,799 INFO    MainThread:14853 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb2847ae610>
2022-04-04 10:54:46,799 INFO    MainThread:14853 [wandb_init.py:init():439] calling init triggers
2022-04-04 10:54:46,799 INFO    MainThread:14853 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-04 10:54:46,799 INFO    MainThread:14853 [wandb_init.py:init():492] starting backend
2022-04-04 10:54:46,800 INFO    MainThread:14853 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-04 10:54:46,840 INFO    MainThread:14853 [backend.py:ensure_launched():219] starting backend process...
2022-04-04 10:54:46,860 INFO    MainThread:14853 [backend.py:ensure_launched():224] started backend process with pid: 15018
2022-04-04 10:54:46,862 INFO    MainThread:14853 [wandb_init.py:init():501] backend started and connected
2022-04-04 10:54:46,897 INFO    MainThread:14853 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-04 10:54:46,897 INFO    MainThread:14853 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-04 10:54:46,897 INFO    MainThread:14853 [wandb_init.py:init():565] updated telemetry
2022-04-04 10:54:46,933 INFO    MainThread:14853 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-04 10:54:47,979 INFO    MainThread:14853 [wandb_run.py:_on_init():1759] communicating current version
2022-04-04 10:54:48,051 INFO    MainThread:14853 [wandb_run.py:_on_init():1763] got version response 
2022-04-04 10:54:48,051 INFO    MainThread:14853 [wandb_init.py:init():625] starting run threads in backend
2022-04-04 10:54:49,414 INFO    MainThread:14853 [wandb_run.py:_console_start():1733] atexit reg
2022-04-04 10:54:49,415 INFO    MainThread:14853 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-04 10:54:49,416 INFO    MainThread:14853 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-04 10:54:49,417 INFO    MainThread:14853 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-04 10:54:49,418 INFO    MainThread:14853 [wandb_init.py:init():664] run started, returning control to user process
2022-04-04 10:54:52,703 INFO    MainThread:14853 [wandb_watch.py:watch():47] Watching
2022-04-04 11:07:47,633 ERROR   MainThread:14853 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2022-04-04 11:53:00,657 INFO    MainThread:14853 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-04 11:53:00,657 INFO    MainThread:14853 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-04 11:53:00,663 INFO    MainThread:14853 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-04 11:53:00,855 INFO    MainThread:14853 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-04 11:53:00,856 INFO    MainThread:14853 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-04 11:53:00,859 INFO    MainThread:14853 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-04 11:53:00,870 INFO    MainThread:14853 [wandb_setup.py:_flush():75] Loading settings from /share/etud/e2008984/.config/wandb/settings
2022-04-04 11:53:00,870 INFO    MainThread:14853 [wandb_setup.py:_flush():75] Loading settings from /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/settings
2022-04-04 11:53:00,870 INFO    MainThread:14853 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-04 11:53:00,870 INFO    MainThread:14853 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-04 11:53:00,870 INFO    MainThread:14853 [wandb_init.py:_log_setup():405] Logging user logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220404_115300-2ks4q7mm/logs/debug.log
2022-04-04 11:53:00,870 INFO    MainThread:14853 [wandb_init.py:_log_setup():406] Logging internal logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220404_115300-2ks4q7mm/logs/debug-internal.log
2022-04-04 11:53:00,870 INFO    MainThread:14853 [wandb_init.py:init():439] calling init triggers
2022-04-04 11:53:00,870 INFO    MainThread:14853 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-04 11:53:00,870 INFO    MainThread:14853 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 3pzfqp1j
2022-04-04 11:53:00,872 INFO    MainThread:14853 [wandb_run.py:finish():1539] finishing run vibferreira/master_thesis/3pzfqp1j
2022-04-04 11:53:00,872 INFO    MainThread:14853 [jupyter.py:save_history():429] not saving jupyter history
2022-04-04 11:53:00,872 INFO    MainThread:14853 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-04 11:53:00,872 INFO    MainThread:14853 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-04-04 11:53:00,872 INFO    MainThread:14853 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-04 11:53:00,875 INFO    MainThread:14853 [wandb_run.py:_restore():1674] restore
2022-04-04 11:53:06,236 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: None
2022-04-04 11:53:08,497 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37190661
  total_bytes: 37192004
}

2022-04-04 11:53:08,705 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37191201
  total_bytes: 37192004
}

2022-04-04 11:53:08,940 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37192004
  total_bytes: 37192004
}

2022-04-04 11:53:10,802 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37202049
  total_bytes: 37851680
}

2022-04-04 11:53:10,917 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37285484
  total_bytes: 37851680
}

2022-04-04 11:53:11,035 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37851680
  total_bytes: 37851680
}

2022-04-04 11:53:11,166 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37851680
  total_bytes: 37851680
}

2022-04-04 11:53:11,290 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37851680
  total_bytes: 37851680
}

2022-04-04 11:53:11,482 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37851680
  total_bytes: 37851680
}

2022-04-04 11:53:11,610 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37851680
  total_bytes: 37851680
}

2022-04-04 11:53:12,667 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37851680
  total_bytes: 37851680
}

2022-04-04 11:53:13,128 INFO    MainThread:14853 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  media_count: 9900
}
pusher_stats {
  uploaded_bytes: 37851680
  total_bytes: 37851680
}
local_info {
}

2022-04-04 11:53:14,903 INFO    MainThread:14853 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-04-04 11:53:14,937 INFO    MainThread:14853 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-04-04 11:53:14,945 INFO    MainThread:14853 [wandb_run.py:_footer_sync_info():2822] logging synced files
